CREATE TABLE student(
    ...
    age INTEGER CHECK (age > 16),
    ...
);
CREATE TABLE student(
    ...
    name TEXT UNIQUE NOT NULL,
    ...
);
CREATE TABLE faculty(
    ...
     name colour TEXT UNIQUE,
    ...
);
CREATE TABLE student(
    ...
     age INTEGER  DEFAULT (age = 20),
    ...
);